---
title: "PartitionDAG Real Data Analysis"
author: "Syed Rahman"
date: "1/21/2019"
output: 
  pdf_document:
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(ggplot2)
library(Matrix)
library(igraph)
library(ggm)
library(sparsebn)
library(lassoshooting)
library(ggm)
library(pdagDFS)
library(partitionDAG)
library(dplyr)
source('graph_plotting_prep.R')
source('other_methods.R')
```

## Partition DAG dairy cattle data

This script includes the dairy cattle data analysis for the partition-DAG paper. 

```{r data_prep, echo=FALSE}
data = read.csv2('data/real_data.csv')
cols_to_keep = c(1,2,3,4,5,6,7,9,10,11,12,15,16,17,18,19,20,21,24,25,26,27,28,29,30)
data = data[,cols_to_keep]

data = scale(data, center = TRUE, scale = TRUE)

known_edges = matrix(c(c('SR','OF'), 
c('SR','MH'),
c('AFI','TFI'),
c('ATS','AMY'),
c('AP','TS'),
c('AP','MH'),
c('NW','AMW'),
c('NW','TSW'),
c('NW','WC'),
c('AP','CH'),
c('NW','WC'),
c('TI','NI')), ncol=2, byrow=TRUE)
graphT = graph_from_edgelist(known_edges, directed = TRUE)
eltrue = apply(get.edgelist(graphT), 1, paste, collapse="-")
```

### 5 group network

In this section we run partition Dag with 5 groups:

```{r network5, echo=TRUE, warning=FALSE, message=FALSE, error=FALSE, results='hide' }
lambda = 0.9
B = partitionDAG::partial5(X = as.matrix(data),
                           l = lambda, 
                           m1 = 6, 
                           m2 = 11, 
                           m3 = 18, 
                           m4 = 23)$B
colnames(B) = colnames(data)
row.names(B) = colnames(data)
#B = B[invPerm(rand_ordr),invPerm(rand_ordr)]
graphB = graph_from_adjacency_matrix(t(B), mode = 'directed', weighted = TRUE, diag = FALSE)
elB = apply(get.edgelist(graphB), 1, paste, collapse="-")
#E(graphB)$color <- ifelse(elB %in% eltrue, "red", "gray80")
plot(graphB, layout = coords5wTI(), vertex.size=15, vertex.label.dist = .1, vertex.color = 'SkyBlue2',
     vertex.label.cex = 0.5, edge.arrow.size = 0.25, edge.curved=.3)
```




```{r network5pclag, echo=TRUE, warning=FALSE, message=FALSE, error=FALSE, results='hide' }
B = pcalg_custom(X = as.matrix(data),
                 a = 0.4868687)$B
colnames(B) = colnames(data)
row.names(B) = colnames(data)
elopp = c("AFI-OF","WI-EVM", "WI-CSC", "NI-TI")
#B = B[invPerm(rand_ordr),invPerm(rand_ordr)]
graphB = graph_from_adjacency_matrix(t(B), mode = 'directed', weighted = TRUE, diag = FALSE)
elB = apply(get.edgelist(graphB), 1, paste, collapse="-")
E(graphB)$color <- ifelse(elB %in% elopp, "red", "gray80")
plot(graphB, layout = coords9wTI(), vertex.size=12, vertex.label.dist = .1, vertex.color = 'SkyBlue2',
     vertex.label.cex = 0.5, edge.arrow.size = 0.4, edge.curved=.4)

```





### 9 group network

In this section we run partition Dag with 10 groups:

```{r network10, echo=TRUE, warning=FALSE, message=FALSE, error=FALSE, results='hide'}
lambda = 0.8
B = partitionDAG::partial9(X = as.matrix(data),
                            l = lambda, 
                            m1 = 2, 
                            m2 = 3, 
                            m3 = 4, 
                            m4 = 6, 
                            m5 = 9,
                            m6 = 11, 
                            m7 = 18, 
                            m8 = 23)$B
colnames(B) = colnames(data)
row.names(B) = colnames(data)
#B = B[invPerm(rand_ordr),invPerm(rand_ordr)]
graphB = graph_from_adjacency_matrix(t(B), mode = 'directed', weighted = TRUE, diag = FALSE)
#elB = apply(get.edgelist(graphB), 1, paste, collapse="-")
#E(graphB)$color <- ifelse(elB %in% eltrue, "red", "gray80")
plot(graphB, layout = coords9wTI(), vertex.size=15, vertex.label.dist = .1, vertex.color = 'SkyBlue2',
     vertex.label.cex = 0.5, edge.arrow.size = 0.25, edge.curved=.3)
```

