---
title: "PartitionDAG Real Data Analysis without TI"
author: "Syed Rahman"
date: "1/21/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(ggplot2)
library(Matrix)
library(igraph)
library(ggm)
library(sparsebn)
library(lassoshooting)
library(ggm)
library(pdagDFS)
library(partitionDAG)
library(dplyr)
source('graph_plotting_prep.R')
```

## Partition DAG dairy cattle data

This script includes the dairy cattle data analysis for the partition-DAG paper. 

```{r data_prep, echo=FALSE}
data = read.csv2('data/real_data.csv')
cols_to_keep = c(1,2,3,4,5,6,7,9,10,11,12,15,16,17,18,19,20,21,24,26,27,28,29,30)
data = data[,cols_to_keep]
rand_ordr = c(1,2,3,4,sample(5:6,2),sample(c(7,8,9),3),sample(10:11,2),sample(12:18,7),
               sample(19:22,4),sample(23:24,2))
inv_rand_ordr = invPerm(rand_ordr)
data = data[,rand_ordr]
```

### 5 group network

In this section we run partition Dag with 5 groups:

```{r network5, echo=TRUE, warning=FALSE, message=FALSE, error=FALSE, results='hide' }
lambda = 4
B = partitionDAG::partial5(X = as.matrix(data),
                           l = lambda, 
                           m1 = 6, 
                           m2 = 11, 
                           m3 = 18, 
                           m4 = 22)$B
colnames(B) = colnames(data)
row.names(B) = colnames(data)
B = B[invPerm(rand_ordr),invPerm(rand_ordr)]
graphB = graph_from_adjacency_matrix(t(B), mode = 'directed', weighted = TRUE, diag = FALSE)
plot(graphB, layout = coords5woTI() , vertex.size=15, vertex.label.dist = .1, vertex.color = 'SkyBlue2',
     vertex.label.cex = 0.5, edge.arrow.size = 0.25, edge.curved=.3)


```



### 10 group network

In this section we run partition Dag with 10 groups:

```{r network10, echo=TRUE, warning=FALSE, message=FALSE, error=FALSE, results='hide'}
lambda = 4
B = partitionDAG::partial9(X = as.matrix(data),
                            l = lambda, 
                            m1 = 2, 
                            m2 = 3, 
                            m3 = 4, 
                            m4 = 6, 
                            m5 = 9,
                            m6 = 11, 
                            m7 = 18, 
                            m8 = 22)$B
colnames(B) = colnames(data)
row.names(B) = colnames(data)
B = B[invPerm(rand_ordr),invPerm(rand_ordr)]
graphB = graph_from_adjacency_matrix(t(B), mode = 'directed', weighted = TRUE, diag = FALSE)
plot(graphB, layout = coords9woTI(), vertex.size=15, vertex.label.dist = .1, vertex.color = 'SkyBlue2',
     vertex.label.cex = 0.5, edge.arrow.size = 0.25, edge.curved=.3)
```

