---
title: "PartitionDAG Real Data Analysis"
author: "Syed Rahman"
date: "1/21/2019"
output: 
  pdf_document:
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(ggplot2)
library(Matrix)
library(igraph)
library(ggm)
library(sparsebn)
library(lassoshooting)
library(ggm)
library(pdagDFS)
library(partitionDAG)
library(dplyr)
source('graph_plotting_prep.R')
source('other_methods.R')
```

## Partition DAG dairy cattle data

This script includes the dairy cattle data analysis for the partition-DAG paper. 

```{r data_prep, echo=FALSE}
data = read.csv2('data/real_data.csv')
cols_to_keep = c(1,2,3,4,5,6,7,9,10,11,15,16,17,18,19,20,21,24,25,26,27,28,29,30)
data = data[,cols_to_keep]
rand_ordr = 1:dim(data)[2]
rand_ordr[1] = 3
rand_ordr[3] = 1
#rand_ordr = c(sample(c(1,2,3,4,5,6),6),sample(c(7,8,9),3),10,sample(11:17,7),
#               sample(18:22,5),sample(23:24,2))
inv_rand_ordr = invPerm(rand_ordr)
data = data[,rand_ordr]

known_edges = matrix(c(c('SR','OF'), 
c('SR','MH'),
c('AFI','TFI'),
c('ATS','AMY'),
c('AP','TS'),
c('AP','MH'),
c('NW','AMW'),
c('NW','TSW'),
c('NW','WC'),
c('AP','CH'),
c('NW','WC'),
c('TI','WI'),
c('TI','NI')), ncol=2, byrow=TRUE)
graphT = graph_from_edgelist(known_edges, directed = TRUE)
plot(graphT, layout = coords5wTI(), vertex.size=15, vertex.label.dist = .1, vertex.color = 'SkyBlue2',
     vertex.label.cex = 0.5, edge.arrow.size = 0.25, edge.curved=.3)
eltrue = apply(get.edgelist(graphT), 1, paste, collapse="-")
```

### 5 group network

In this section we run partition Dag with 5 groups:

```{r network5, echo=TRUE, warning=FALSE, message=FALSE, error=FALSE, results='hide' }
lambda = 4
B = partitionDAG::partial5(X = as.matrix(data),
                           l = lambda, 
                           m1 = 6, 
                           m2 = 10, 
                           m3 = 17, 
                           m4 = 22)$B
colnames(B) = colnames(data)
row.names(B) = colnames(data)
B = B[invPerm(rand_ordr),invPerm(rand_ordr)]
graphB = graph_from_adjacency_matrix(t(B), mode = 'directed', weighted = TRUE, diag = FALSE)
elB = apply(get.edgelist(graphB), 1, paste, collapse="-")
E(graphB)$color <- ifelse(elB %in% eltrue, "red", "gray80")
plot(graphB, layout = coords5wTI(), vertex.size=15, vertex.label.dist = .1, vertex.color = 'SkyBlue2',
     vertex.label.cex = 0.5, edge.arrow.size = 0.25, edge.curved=.3)
```

```{r network5, echo=TRUE, warning=FALSE, message=FALSE, error=FALSE, results='hide' }
lambda = 0.01
B = partitionDAG::partial5_inc(X = as.matrix(data),
                           l = lambda, 
                           m1 = 6, 
                           m2 = 10, 
                           m3 = 17, 
                           m4 = 22,
                           l1= 1, l2= 2, l3= 1000, l4= 20000,
                           )$B
colnames(B) = colnames(data)
row.names(B) = colnames(data)
B = B[invPerm(rand_ordr),invPerm(rand_ordr)]
graphB = graph_from_adjacency_matrix(t(B), mode = 'directed', weighted = TRUE, diag = FALSE)
elB = apply(get.edgelist(graphB), 1, paste, collapse="-")
E(graphB)$color <- ifelse(elB %in% eltrue, "red", "gray80")
plot(graphB, layout = coords5wTIwoSM(), vertex.size=15, vertex.label.dist = .1, vertex.color = 'SkyBlue2',
     vertex.label.cex = 0.5, edge.arrow.size = 0.25, edge.curved=.4)


```

```{r network5, echo=TRUE, warning=FALSE, message=FALSE, error=FALSE, results='hide' }
lambda = 0.1
B = partitionDAG::partial5_inc(X = as.matrix(data),
                           l = lambda, 
                           m1 = 6, 
                           m2 = 10, 
                           m3 = 17, 
                           m4 = 22,
                           l1= 1, l2= 1, l3= 100, l4= 100,
                           )$B
colnames(B) = colnames(data)
row.names(B) = colnames(data)
B = B[invPerm(rand_ordr),invPerm(rand_ordr)]
graphB = graph_from_adjacency_matrix(t(B), mode = 'directed', weighted = TRUE, diag = FALSE)
elB = apply(get.edgelist(graphB), 1, paste, collapse="-")
E(graphB)$color <- ifelse(elB %in% eltrue, "red", "gray80")
plot(graphB, layout = coords5wTI(), vertex.size=15, vertex.label.dist = .1, vertex.color = 'SkyBlue2',
     vertex.label.cex = 0.5, edge.arrow.size = 0.25, edge.curved=.4)
```


```{r network5, echo=TRUE, warning=FALSE, message=FALSE, error=FALSE, results='hide' }
lambda = 2
B = partitionDAG::partial5_inc(X = as.matrix(data),
                           l = lambda, 
                           m1 = 6, 
                           m2 = 11, 
                           m3 = 18, 
                           m4 = 23,
                           l1= 1, l2= 100, l3= 200, l4= 300,
                           )$B
colnames(B) = colnames(data)
row.names(B) = colnames(data)
B = B[invPerm(rand_ordr),invPerm(rand_ordr)]
graphB = graph_from_adjacency_matrix(t(B), mode = 'directed', weighted = TRUE, diag = FALSE)
elB = apply(get.edgelist(graphB), 1, paste, collapse="-")
E(graphB)$color <- ifelse(elB %in% eltrue, "red", "gray80")
plot(graphB, layout = coords5wTI(), vertex.size=15, vertex.label.dist = .1, vertex.color = 'SkyBlue2',
     vertex.label.cex = 0.5, edge.arrow.size = 0.25, edge.curved=.4)
```




```{r network5pdag, echo=TRUE, warning=FALSE, message=FALSE, error=FALSE, results='hide' }
B = pcalg_custom(X = as.matrix(data),
                 a = 0.999)$B
colnames(B) = colnames(data)
row.names(B) = colnames(data)
B = B[invPerm(rand_ordr),invPerm(rand_ordr)]
graphB = graph_from_adjacency_matrix(t(B), mode = 'directed', weighted = TRUE, diag = FALSE)
elB = apply(get.edgelist(graphB), 1, paste, collapse="-")
E(graphB)$color <- ifelse(elB %in% eltrue, "red", "gray80")
plot(graphB, layout = coords5wTIwoSM(), vertex.size=15, vertex.label.dist = .1, vertex.color = 'SkyBlue2',
     vertex.label.cex = 0.5, edge.arrow.size = 0.25, edge.curved=.3)


```

```{r network5pdagBGt, echo=TRUE, warning=FALSE, message=FALSE, error=FALSE, results='hide' }
B = pcalg_addBG5_t(X = as.matrix(data),
                 a = 0.999,
                 m1 = 6, 
                 m2 = 11, 
                 m3 = 18, 
                 m4 = 23)$B
colnames(B) = colnames(data)
row.names(B) = colnames(data)
B = B[invPerm(rand_ordr),invPerm(rand_ordr)]
graphB = graph_from_adjacency_matrix(t(B), mode = 'directed', weighted = TRUE, diag = FALSE)
elB = apply(get.edgelist(graphB), 1, paste, collapse="-")
E(graphB)$color <- ifelse(elB %in% eltrue, "red", "gray80")
plot(graphB, layout = coords5wTI(), vertex.size=15, vertex.label.dist = .1, vertex.color = 'SkyBlue2',
     vertex.label.cex = 0.5, edge.arrow.size = 0.25, edge.curved=.3)


```

```{r network5pdagBG, echo=TRUE, warning=FALSE, message=FALSE, error=FALSE, results='hide' }
B = pcalg_addBG5(X = as.matrix(data),
                 a = 0.99,
                 m1 = 6, 
                 m2 = 11, 
                 m3 = 18, 
                 m4 = 23)$B
colnames(B) = colnames(data)
row.names(B) = colnames(data)
B = B[invPerm(rand_ordr),invPerm(rand_ordr)]
graphB = graph_from_adjacency_matrix(t(B), mode = 'directed', weighted = TRUE, diag = FALSE)
plot(graphB, layout = coords5wTI(), vertex.size=15, vertex.label.dist = .1, vertex.color = 'SkyBlue2',
     vertex.label.cex = 0.5, edge.arrow.size = 0.25, edge.curved=.3)


```


### 10 group network

In this section we run partition Dag with 10 groups:

```{r network10, echo=TRUE, warning=FALSE, message=FALSE, error=FALSE, results='hide'}
lambda = 4
B = partitionDAG::partial9(X = as.matrix(data),
                            l = lambda, 
                            m1 = 2, 
                            m2 = 3, 
                            m3 = 4, 
                            m4 = 6, 
                            m5 = 9,
                            m6 = 11, 
                            m7 = 18, 
                            m8 = 23)$B
colnames(B) = colnames(data)
row.names(B) = colnames(data)
B = B[invPerm(rand_ordr),invPerm(rand_ordr)]
graphB = graph_from_adjacency_matrix(t(B), mode = 'directed', weighted = TRUE, diag = FALSE)
plot(graphB, layout = coords9wTI(), vertex.size=15, vertex.label.dist = .1, vertex.color = 'SkyBlue2',
     vertex.label.cex = 0.5, edge.arrow.size = 0.25, edge.curved=.3)
```

